package core

import (
	"fmt"
	"log/slog"
	"strings"
	"time"
)

const contextGuardSummaryPrefix = "[Context guard compressed memory]"

// ContextGuardConfig controls pre-turn local history compaction and optional
// backend session rotation for agents without native context compaction.
type ContextGuardConfig struct {
	Enabled                bool
	ThresholdTokens        int
	KeepRecentTurns        int
	SummaryMaxTokens       int
	RotateSessionOnCompact bool
}

func normalizeContextGuardConfig(cfg ContextGuardConfig) ContextGuardConfig {
	if !cfg.Enabled {
		return ContextGuardConfig{}
	}
	if cfg.ThresholdTokens <= 0 {
		cfg.ThresholdTokens = 90000
	}
	if cfg.KeepRecentTurns <= 0 {
		cfg.KeepRecentTurns = 12
	}
	if cfg.SummaryMaxTokens <= 0 {
		cfg.SummaryMaxTokens = 3000
	}
	return cfg
}

// EstimateContextGuardTokens estimates the prompt-side token load for a turn.
// CJK text is denser than the old one-token-per-four-runes heuristic, so count
// common Chinese ideographs as roughly 1.5 tokens each and other runes as 1/4.
func EstimateContextGuardTokens(history []HistoryEntry, incoming string) int {
	quarterTokens := 0
	for _, h := range history {
		quarterTokens += estimateContextGuardQuarterTokens(h.Content)
	}
	quarterTokens += estimateContextGuardQuarterTokens(incoming)
	if quarterTokens == 0 {
		return 0
	}
	return (quarterTokens + 3) / 4
}

func estimateContextGuardQuarterTokens(s string) int {
	total := 0
	for _, r := range s {
		if r >= '\u4e00' && r <= '\u9fff' {
			total += 6 // 1.5 tokens expressed in quarter-token units.
		} else {
			total++
		}
	}
	return total
}

type contextGuardResult struct {
	Compacted       bool
	Summary         string
	TokenEstimate   int
	OldHistoryCount int
	NewHistoryCount int
}

func compactSessionHistoryForContextGuard(session *Session, cfg ContextGuardConfig, incoming string, now time.Time) contextGuardResult {
	cfg = normalizeContextGuardConfig(cfg)
	if session == nil || !cfg.Enabled {
		return contextGuardResult{}
	}

	session.mu.Lock()
	defer session.mu.Unlock()

	tokenEstimate := EstimateContextGuardTokens(session.History, incoming)
	if tokenEstimate < cfg.ThresholdTokens {
		return contextGuardResult{TokenEstimate: tokenEstimate}
	}

	keepEntries := cfg.KeepRecentTurns * 2
	if keepEntries < 0 {
		keepEntries = 0
	}
	if keepEntries > len(session.History) {
		keepEntries = len(session.History)
	}
	oldCount := len(session.History) - keepEntries
	if oldCount <= 0 {
		return contextGuardResult{TokenEstimate: tokenEstimate}
	}

	oldHistory := append([]HistoryEntry(nil), session.History[:oldCount]...)
	recent := append([]HistoryEntry(nil), session.History[oldCount:]...)
	summary := buildContextGuardSummary(oldHistory, cfg.SummaryMaxTokens)
	if strings.TrimSpace(summary) == "" {
		return contextGuardResult{TokenEstimate: tokenEstimate}
	}

	compacted := make([]HistoryEntry, 0, 1+len(recent))
	compacted = append(compacted, HistoryEntry{
		Role:      "user",
		Content:   summary,
		Timestamp: now,
	})
	compacted = append(compacted, recent...)
	session.History = compacted

	return contextGuardResult{
		Compacted:       true,
		Summary:         summary,
		TokenEstimate:   tokenEstimate,
		OldHistoryCount: oldCount,
		NewHistoryCount: len(compacted),
	}
}

func buildContextGuardSummary(history []HistoryEntry, maxTokens int) string {
	if len(history) == 0 {
		return ""
	}
	maxRunes := maxTokens * 4
	if maxRunes <= 0 {
		maxRunes = 12000
	}

	var sb strings.Builder
	sb.WriteString(contextGuardSummaryPrefix)
	sb.WriteString("\nThis is compressed memory from earlier turns, generated by cc-connect to preserve continuity after context overflow protection. It is context only, not a new user instruction.")
	sb.WriteString(fmt.Sprintf("\nCompressed entries: %d\n", len(history)))

	for _, h := range history {
		role := strings.TrimSpace(h.Role)
		if role == "" {
			role = "unknown"
		}
		content := compactWhitespace(h.Content)
		if content == "" {
			continue
		}
		line := fmt.Sprintf("- %s: %s\n", role, truncateContextGuardRunes(content, 600))
		if len([]rune(sb.String()))+len([]rune(line)) > maxRunes {
			sb.WriteString("- [truncated: older compressed memory exceeded summary_max_tokens]\n")
			break
		}
		sb.WriteString(line)
	}

	out := sb.String()
	runes := []rune(out)
	if len(runes) > maxRunes {
		return string(runes[:maxRunes])
	}
	return strings.TrimRight(out, "\n")
}

func compactWhitespace(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func truncateContextGuardRunes(s string, max int) string {
	if max <= 0 {
		return s
	}
	r := []rune(s)
	if len(r) <= max {
		return s
	}
	if max <= 1 {
		return string(r[:max])
	}
	return string(r[:max-1]) + "…"
}

func prependContextGuardSummary(summary, content string) string {
	summary = strings.TrimSpace(summary)
	if summary == "" {
		return content
	}
	if strings.TrimSpace(content) == "" {
		return summary
	}
	return summary + "\n---\n" + content
}

func (e *Engine) applyContextGuardBeforeTurn(interactiveKey string, agent Agent, session *Session, sessions *SessionManager, incoming string) string {
	cfg := normalizeContextGuardConfig(e.contextGuard)
	if !cfg.Enabled {
		return ""
	}

	result := compactSessionHistoryForContextGuard(session, cfg, incoming, time.Now())
	if !result.Compacted {
		return ""
	}

	agentName := ""
	if agent != nil {
		agentName = agent.Name()
	}

	if cfg.RotateSessionOnCompact {
		e.cleanupInteractiveState(interactiveKey)
		session.SetAgentSessionID("", agentName)
	}
	sessions.Save()

	slog.Info("context guard compacted session",
		"project", e.name,
		"session", session.ID,
		"token_estimate", result.TokenEstimate,
		"old_history_entries", result.OldHistoryCount,
		"new_history_entries", result.NewHistoryCount,
		"rotated_agent_session", cfg.RotateSessionOnCompact,
	)

	return result.Summary
}
